apiVersion: v1
kind: Service
metadata:
  name: koop-databricks
  labels:
    app: koop-databricks
spec:
  type: LoadBalancer  # Use ClusterIP for internal-only or NodePort for specific node access
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: koop-databricks
  sessionAffinity: None
